const francmin = () => require('franc-min')
const franc = () => require('franc')
const francall = () => require('franc-all')

const மொழிகள் = {
  'francmin': ['cmn', 'spa', 'eng', 'rus', 'arb', 'ben', 'hin', 'por', 'ind', 'jpn', 'fra', 'deu', 'jav', 'kor', 'tel', 'vie', 'mar', 'ita', 'tam', 'tur', 'urd', 'guj', 'pol', 'ukr', 'fas', 'kan', 'mai', 'mal', 'mya', 'ori', 'gax', 'swh', 'sun', 'ron', 'pan', 'bho', 'amh', 'hau', 'fuv', 'bos', 'bos', 'hrv', 'nld', 'srp', 'srp', 'tha', 'ckb', 'yor', 'uzn', 'uzn', 'zlm', 'zlm', 'ibo', 'nep', 'ceb', 'skr', 'tgl', 'hun', 'azj', 'azj', 'sin', 'koi', 'ell', 'ces', 'run', 'bel', 'plt', 'qug', 'mad', 'nya', 'zyb', 'pbu', 'kin', 'zul', 'bul', 'swe', 'lin', 'som', 'hms', 'hnj', 'ilo', 'kaz'],
  'franc': ['uig', 'uig', 'hat', 'khm', 'aka', 'hil', 'sna', 'tat', 'xho', 'hye', 'min', 'afr', 'lua', 'sat', 'bod', 'tir', 'fin', 'slk', 'tuk', 'tuk', 'dan', 'nob', 'suk', 'als', 'sag', 'nno', 'heb', 'mos', 'tgk', 'cat', 'sot', 'kat', 'bcl', 'glg', 'lao', 'lit', 'umb', 'tsn', 'vec', 'nso', 'ban', 'bug', 'knc', 'kng', 'ibb', 'lug', 'ace', 'bam', 'tzm', 'ydd', 'kmb', 'lun', 'shn', 'war', 'dyu', 'wol', 'kir', 'nds', 'fuf', 'mkd', 'vmw', 'zgh', 'ewe', 'khk', 'slv', 'ayr', 'bem', 'emk', 'bci', 'bum', 'epo', 'pam', 'tiv', 'tpi', 'ven', 'ssw', 'nyn', 'kbd', 'iii', 'yao', 'lav', 'quz', 'src', 'sco', 'tso', 'rmy', 'men', 'fon', 'nhn', 'dip', 'kde', 'snn', 'kbp', 'tem', 'toi', 'est', 'snk', 'cjk', 'ada', 'aii', 'quy', 'rmn', 'bin', 'gaa', 'ndo'],
  'francall': ['nym', 'sus', 'tly', 'srr', 'kha', 'hea', 'gkp', 'hni', 'fry', 'yua', 'fij', 'fur', 'tet', 'wln', 'eus', 'oss', 'nbl', 'pov', 'cym', 'lus', 'dag', 'dga', 'bre', 'kek', 'lij', 'pcd', 'roh', 'bfa', 'kri', 'cnh', 'lob', 'arn', 'bba', 'dzo', 'kea', 'sah', 'smo', 'koo', 'nzi', 'maz', 'pis', 'ctd', 'cos', 'ltz', 'lia', 'mlt', 'hna', 'zdj', 'guc', 'qwh', 'quc', 'div', 'isl', 'kqn', 'pap', 'gle', 'dyo', 'hns', 'gjn', 'njo', 'hus', 'mag', 'xsm', 'ote', 'qxn', 'tyv', 'gag', 'san', 'shk', 'nba', 'miq', 'mam', 'tah', 'nav', 'ami', 'lot', 'cak', 'tzh', 'tzo', 'lns', 'ton', 'tbz', 'lad', 'vai', 'mto', 'ady', 'abk', 'ast', 'tsz', 'swb', 'cab', 'krl', 'zam', 'top', 'cha', 'crs', 'ddn', 'loz', 'mri', 'hsb', 'cri', 'pbb', 'alt', 'qva', 'mxv', 'gla', 'kjh', 'csw', 'qvm', 'fao', 'kal', 'cni', 'chk', 'mah', 'rar', 'evn', 'qvn', 'wwa', 'buc', 'qvh', 'toj', 'lue', 'qvc', 'ojb', 'jiv', 'qud', 'lld', 'hlt', 'que', 'pon', 'agr', 'qxa', 'quh', 'tca', 'chj', 'ike', 'kwi', 'rgn', 'oki', 'tob', 'guu', 'qxu', 'pau', 'shp', 'gld', 'gug', 'mzi', 'cjs', 'mic', 'haw', 'eve', 'yap', 'cbt', 'ame', 'gyr', 'vep', 'cpu', 'acu', 'not', 'sme', 'yad', 'ura', 'cbu', 'huu', 'cof', 'boa', 'ztu', 'piu', 'cbr', 'mcf', 'bis', 'orh', 'ykg', 'ese', 'nio', 'cic', 'csa', 'mcd', 'amc', 'amr', 'cot', 'oaa', 'ajg', 'arl', 'ppl', 'bax', 'nku', 'cbi', 'ccp', 'chr', 'chr', 'duu', 'cfm', 'fat', 'ido', 'ina', 'kkh', 'ktu', 'fkv', 'lat', 'glv', 'mfq', 'mnw', 'mxi', 'pcm', 'niu', 'kqs', 'sey', 'ekk', 'lvs', 'blt', 'kdh', 'tdt', 'twi', 'auc', 'gaz', 'pnb', 'zro']
}

export async function franc_பெறு(மொழி) {
  if (மொழிகள்['francmin'].includes(மொழி)) return await francmin()
  if (மொழிகள்['franc'].includes(மொழி)) return await franc()
  if (மொழிகள்['francall'].includes(மொழி)) return await francall()
}
